### PR TITLE
Command line flags

### LINKED ISSUE #11: Add `--x64` command line flag
Analogous to `--aarch64`, we should have a command-line flag to run named rules with the x86-64 prelude files. The files you'll need to add can be found by looking at the `test_x64_rule_with_lhs_termname` and related test cases. 

The goal is to be able to run commands like this:

```
cargo run -- --x64 --term iadd --names iadd_base_case_32_or_64_lea --widths I64
```

Which currently fails with:
```
error: Found argument '--x64' which wasn't expected, or isn't valid in this context
```

### PR DESCRIPTION
**Pull request by vaishuc17**
We added processing for --x64 and --widths flags. Fixes #11

### CODE REVIEW

File: cranelift/isle/veri/veri_engine/src/main.rs [hunk 1]
```diff
@@ -17,6 +17,9 @@ struct Args {
     #[clap(short, long, default_value = "lower")]
     term: String,
 
+    #[clap(long)]
+    widths: Option<Vec<String>>,
```
Comment (avanhatt) [inline cranelift/isle/veri/veri_engine/src/main.rs:22]: Can you add a comment explaining what this flag does?

File: cranelift/isle/veri/veri_engine/src/verify.rs [hunk 2]
```diff
@@ -31,7 +31,41 @@ pub fn verify_rules(inputs: Vec<PathBuf>, config: &Config) {
         .expect(format!("Missing term width for {}", config.term).as_str())
         .clone();
 
-    for type_instantiation in types {
+    // if let Some(_) = widths {
+    //     match(&widths.unwrap()) {
+    //         _ =>
+    //     }
+    // }
```
Comment (avanhatt) [inline cranelift/isle/veri/veri_engine/src/verify.rs]: Please remove this commented-out code.

File: cranelift/isle/veri/veri_engine/src/verify.rs [hunk 3]
```diff
@@ -31,7 +31,41 @@ pub fn verify_rules(inputs: Vec<PathBuf>, config: &Config) {
...
+
+        types
+            .into_iter()
+            .filter(|t| {
+                if let Some(canonical_type) = &t.canonical_type {
+                    width_types.contains(canonical_type)
+                } else {
+                    false
+                }
+            })
```
Comment (avanhatt) [inline cranelift/isle/veri/veri_engine/src/verify.rs:56]: Good use of filter!

**Review by avanhatt — CHANGES_REQUESTED** [review]

**Review by avanhatt — APPROVED** [review]
Looks good know! You can now resolve the conflicts and merge.
